# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b17104891d5aa544ddad04571c53d2cc58679c2b7f1d9f0f5fe5f0e88021603999e0ae79b2c48a379c87d5099725ed65f11641ea8c69b63652fb67ea0fa3f1bd

test:
  secret_key_base: 7b047e1b76f1c34f958f494ea8168ac16b480568cbcd2beabe2f355c1d635693f43ca6e80f151d7ebce7783fd745c9f4186400c3e99ef0d1bf8404448fef5680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
